{"aid": "iln9rzc183x1rm", "result": {"folders": ["lab5"], "unique_views": 48, "request_instructor_me": false, "change_log": [{"data": "ia7ywxlotef5l4", "anon": "no", "when": "2015-05-28T09:18:03Z", "uid": "i6z6k9yt7b77nz", "type": "create"}, {"uid": "i6z6k9yt7b77nz", "data": "ia7zvxy317n3pc", "when": "2015-05-28T09:45:17Z", "to": "ia7ywxlljsb5l2", "anon": "no", "type": "s_answer"}, {"uid": "hs2swpdtr91gu", "data": "iada0q3ysfk4d3", "when": "2015-06-01T02:27:47Z", "to": "ia7ywxlljsb5l2", "anon": "no", "type": "i_answer"}, {"to": "ia7ywxlljsb5l2", "anon": "no", "when": "2016-03-05T07:32:34Z", "uid": "i0c1nsm3911wc", "type": "followup"}], "upvote_ids": [], "id": "ia7ywxlljsb5l2", "bookmarked": 4, "no_answer": 0, "i_edits": [], "is_bookmarked": false, "children": [{"folders": [], "is_tag_endorse": false, "created": "2015-05-28T09:45:17Z", "config": {}, "tag_endorse_arr": [], "children": [], "bucket_name": "Today", "type": "s_answer", "tag_endorse": [], "bucket_order": 2, "data": {"embed_links": []}, "id": "ia7zvxy0lo63pb", "history": [{"content": "<p>补充&#xff1a;</p>\n<p>debug的时候看起来是&#xff0c;调用do_exit的时候&#xff0c;把initproc也关掉了。</p>\n<p></p>\n<p></p>\n<p>qemu:</p>\n<p>kernel panic at kern/process/proc.c:461:<br /> initproc exit.</p>\n<p></p>\n<p>code:</p>\n<p>if (current == initproc) {<br /> panic(&#34;initproc exit.\\n&#34;);<br /> }</p>\n<p></p>\n<p>然后就没头绪了。。。</p>", "anon": "no", "subject": "", "uid": "i6z6k9yt7b77nz", "created": "2015-05-28T09:45:17Z"}]}, {"folders": [], "is_tag_endorse": false, "created": "2015-06-01T02:27:47Z", "config": {}, "tag_endorse_arr": [], "children": [], "bucket_name": "Today", "type": "i_answer", "tag_endorse": [], "bucket_order": 2, "data": {"embed_links": []}, "id": "iada0q3xril4d2", "history": [{"content": "<p>check_slab应该已经从评分函数里删除了&#xff0c;可以更新一下基准代码</p>", "anon": "no", "subject": "", "uid": "hs2swpdtr91gu", "created": "2015-06-01T02:27:47Z"}]}, {"folders": [], "updated": "2016-03-05T07:32:34Z", "no_upvotes": 0, "uid": "i0c1nsm3911wc", "created": "2016-03-05T07:32:34Z", "type": "followup", "no_answer": 0, "id": "iletbi46tvjvj", "anon": "no", "bucket_name": "Today", "config": {}, "bucket_order": 2, "data": null, "children": [], "subject": "<p>把作业目录下lab5的grade.sh拷贝到答案目录下lab5的grade.sh</p>"}], "no_answer_followup": 0, "nr": 462, "bucket_order": 2, "config": {}, "status": "active", "tags": ["lab5", "student"], "num_favorites": 0, "bucket_name": "Today", "q_edits": [], "data": {"embed_links": []}, "request_instructor": 0, "created": "2015-05-28T09:18:03Z", "is_tag_good": false, "type": "question", "s_edits": [], "my_favorite": false, "default_anonymity": "no", "t": 1457674526881, "tag_good": [], "tag_good_arr": [], "history": [{"content": "<p>RT </p>\n<p>对于每一个任务都会报这个错。</p>\n<p></p>\n<p>!! error: missing &#39;check_slab() succeeded!&#39;</p>\n<p></p>\n<p>我看了下&#xff0c;这个应该是pmm_init()函数运行到最后的kmalloc_init()时才会产生的success。说明程序中途就退出了&#xff0c;但是我不知道继续怎么调试了……</p>", "anon": "no", "subject": "Lab5 make grade的时候会报错", "uid": "i6z6k9yt7b77nz", "created": "2015-05-28T09:18:03Z"}]}, "error": null}